# Generated by Django 4.0.4 on 2024-02-03 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_groups_alter_user_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coderecoverpassword',
            name='code',
            field=models.IntegerField(verbose_name='Codigo de seguridad'),
        ),
    ]
