version: '3.1'

services:
  app-example:
    build: .
    image: app-example:latest
    container_name: app-example
    environment:
      ENVIRONMENT: development
    depends_on:
      - db
    volumes:
      - .:/src
      - ./scripts:/scripts
    # Dev account: admin pass: admin
    command: ["/scripts/wait-for-it.sh", "db:5432", "--", "/scripts/command-dev.sh"]
    ports:
      - "8000:8000"

  db:
    image: postgres:12
    container_name: app-example-postgres
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
