# Generated by Django 4.0.4 on 2024-02-03 06:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emergency', '0002_emergencycategory_emergency_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emergency',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emergency.emergencycategory'),
        ),
    ]
